### ISSUE TITLE
only 198 of 1,958 songs are showing

### ISSUE THREAD

**Issue by anahawie** [theyak/ytmixer#1]
![image](https://github.com/theyak/ytmixer/assets/104401868/76eb0f0e-5b2e-4aaf-9e6f-38b83ab5d6e9)
![image](https://github.com/theyak/ytmixer/assets/104401868/259028df-9e65-40c6-9f0a-ec74232ea36d)

i also noticed no matter how many times i click shuffle, it seems like the first hundred of my playlists are only getting shuffled, i never saw any of the music that i have saved at the bottom of my entire playlists. i tried scrolling down, but it doesn't load anything.. 

also only 23 of my playlists are loaded too, i have over 50. am i missing something?

**Comment by theyak** [comment]
Oh, hi! I kind of forgot about this project. I shuffled my playlist, saved it, and never really used it again. I didn't know anyone even knew about this. I have no idea what would be causing the issues you are seeing. Is your playlist public? If so, I can try loading it to see what happens if you can provide the playlist ID, which should be shown in the URL of the page. Also, are you running this locally on your machine or via the Netlify URL?

**Comment by theyak** [comment]
A couple of fixes have just been pushed. Can you try again?

**Comment by theyak** [comment]
Closing due to no response from original reporter.
